spring:
  application:
    name: springcloud-gateway
  main:
    ### spring.main.allow-bean-definition-overriding=true就是解决bean重复定义的。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  sleuth:
    sampler: # 样本配置
      # 百分比，默认为0.1
      probability: 1.0
      # 速率，每秒追踪30次
      rate: 30
  zipkin:
    base-url: http://localhost:9412
    sender:
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: luobo
    password: luobo123
  cloud:
    gateway:
      httpclient:
        ssl:
          ### 注：uri为https的请求需要配置证书，可通过设置spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager=true关闭ssl认证，默认为false
          use-insecure-trust-manager: true
      discovery:
        locator:
          lower-case-service-id: true # 兼容Zuul 升级到 Spring Cloud Gateway；服务名称小写配置, 默认为false
          enabled: true # 默认会为所有服务都进行转发操作
      routes:
      - id: eureka-server
        #  lb 代表从注册中心获取服务 后面接的就是你需要转发到的服务名称，这个服务名称必须跟 Eureka 中的对应，否则会找不到服务
        uri: lb://eureka-server
        predicates:
          - Path=/eureka-server/**
        filters:
          - StripPrefix=1
      - id: resource-server
        uri: lb://resource-server
        predicates:
          - Path=/resource-server/**
        filters:
          - StripPrefix=1
server:
  port: 3234
  shutdown: graceful

### 暴露端点
management:
  endpoints:
    web:
      exposure:
        ### 在YAML中有特殊的含义，所以如果要包含(或排除)所有端点，请务必添加引号
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://luobo:luobo123@localhost:1234/eureka
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 90 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
logging:
  level:
    root: info