spring:
  application:
    name: springcloud-gateway
  main:
    ### spring.main.allow-bean-definition-overriding=true就是解决bean重复定义的。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    gateway:
      httpclient:
        ssl:
          ### 注：uri为https的请求需要配置证书，可通过设置spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager=true关闭ssl认证，默认为false
          use-insecure-trust-manager: true

server:
  port: 6666
  shutdown: graceful

### 暴露端点
management:
  endpoints:
    web:
      exposure:
        ### 在YAML中有特殊的含义，所以如果要包含(或排除)所有端点，请务必添加引号
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://luobo:luobo123@localhost:1111/eureka
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 10  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    # 此处的metadata-map 一定要配置，否则会报错；作用：将用户验证信息同步到Eureka服务器，这样其他服务实例就可以通过这些信息访问Admin服务端了
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}